<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.9.10 setup script
 * Date: Thu, 13 Oct 2022 12:39:12 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: archaeodataspace [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'archaeodataspace';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['ssl'] = false;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['AllowNoPassword'] = true;
$cfg['Servers'][$i]['password'] = '20GaVSFqR8lA';
$cfg['Servers'][$i]['SignonSession'] = 'pma';
$cfg['Servers'][$i]['SignonURL'] = 'https://archaeodata.space/pma/';
$cfg['Servers'][$i]['LogoutURL'] = 'https://archaeodata.space/pma/';
$cfg['Servers'][$i]['auth_http_realm'] = 'archaeodataspace';

/* End of servers configuration */

$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['blowfish_secret'] = 'zfr\\7)^Euf=,1)^5}\'}(`Xh)0~t|"R-}';
$cfg['UserprefsDisallow'] = array('Servers/1/only_db', 'Servers/1/hide_db');
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['ZipDump'] = false;
$cfg['BZipDump'] = false;
?>
